name: Install crane
description: >-
  Installs the 'crane' Docker utility application.

runs:
  using: composite
  steps:
    - name: Install crane
      shell: bash
      run: |
        VERSION=v0.20.2
        CHECKSUM=c14340087103ba9dadf61d45acd20675490fd0ccbd56ac7901fc1b502137f44b
        OS=Linux
        ARCH=x86_64
        URL="https://github.com/google/go-containerregistry/releases/download/${VERSION}/go-containerregistry_${OS}_${ARCH}.tar.gz"

        # return early if already installed
        which -s crane && exit 0 || true

        # download
        curl -sSL "$URL" > /tmp/go-containerregistry.tar.gz

        # verify checksum
        DOWNLOADED_CHECKSUM=$(sha256sum /tmp/go-containerregistry.tar.gz | cut -d' ' -f1)
        if [ "${DOWNLOADED_CHECKSUM}" != "${CHECKSUM}" ]; then
          echo "::error::Aborting due to checksum mismatch for '$URL': expected=CHECKSUM; actual=DOWNLOADED_CHECKSUM"
          exit 1
        fi

        # extract and install the 'crane' binary
        tar -xzf /tmp/go-containerregistry.tar.gz -C /tmp crane
        sudo install /tmp/crane /usr/local/bin/

        echo "Successfully installed crane ${VERSION}"
