name: Set the version for build artifacts
description: >-
  Sets the version for build artifacts based on user input or commit SHA.

inputs:
  version:
    description: The version of build artifacts
    required: false

runs:
  using: composite
  steps:
    - name: Set version
      shell: bash
      run: |
        if [ -n "${{ inputs.version }}" ]; then
          VERSION="${{ inputs.version }}"
          echo "::notice::Version specified: '$VERSION'"
        elif [ -n "${{ github.event.workflow_run.head_sha }}" ]; then
          VERSION="${{ github.event.workflow_run.head_sha }}"
          echo "::notice::Version derived from workflow_run event: '$VERSION'"
        elif [ -n "${{ github.event.pull_request.head.sha }}" ]; then
          VERSION="${{ github.event.pull_request.head.sha }}"
          echo "::notice::Version derived from pull_request event: '$VERSION'"
        else
          VERSION="$(echo ${{ github.sha }} | cut -c1-8)"
          echo "::notice::Version derived from github.sha: '$VERSION'"
        fi
        echo VERSION="$VERSION" >> $GITHUB_ENV
