name: Deploy service
description: >-
  Copies the service's Docker image to the target environment's ECR repository, tags the image with
  'latest' and updates the ECS service, forcing a new deployment to happen.

inputs:
  version:
    description: The version of the service and its build artifacts
    required: true
  environment:
    description: The name of the GitHub environment to which the service is being deployed
    required: true
  prerequisite-environment:
    description: The name of the GitHub environment that must have a successful prior deployment
    required: true
  deployment-payload-marker:
    description: Marker used to identify deployments created by this action
    required: false
    default: github-actions-deploy

runs:
  using: composite
  steps:
    - name: Verify prerequisite deployment
      uses: ./.github/actions/verify-prerequisite-deployment
      with:
        version: ${{ inputs.version }}
        deployment-environment: ${{ inputs.environment }}
        prerequisite-environment: ${{ inputs.prerequisite-environment }}
        deployment-payload-marker: ${{ inputs.deployment-payload-marker }}

    - name: Create GitHub deployment
      uses: chrnorm/deployment-action@55729fcebec3d284f60f5bcabbd8376437d696b1  # v2.0.7
      id: create-deployment
      with:
        token: ${{ github.token }}
        environment: ${{ inputs.environment }}
        payload: '"${{ inputs.deployment-payload-marker }}"'

    - name: Clean up redundant GitHub deployments
      uses: ./.github/actions/cleanup-redundant-deployments
      with:
        version: ${{ inputs.version }}
        deployment-environment: ${{ inputs.environment }}
        deployment-payload-marker: ${{ inputs.deployment-payload-marker }}

    - name: Update deployment status (in progress)
      if: success()
      uses: chrnorm/deployment-status@9a72af4586197112e0491ea843682b5dc280d806  # v2.0.3
      with:
        token: ${{ github.token }}
        deployment-id: ${{ steps.create-deployment.outputs.deployment_id }}
        state: in_progress

    - name: Deploy
      shell: bash
      run: |
        echo deploying version '${{ inputs.version }}'
        # false
        sleep 5
        echo "deployment completed"

    - name: sleep before success
      shell: bash
      run: |
        sleep 30

    - name: Update deployment status (success)
      if: success()
      uses: chrnorm/deployment-status@9a72af4586197112e0491ea843682b5dc280d806  # v2.0.3
      with:
        token: ${{ github.token }}
        deployment-id: ${{ steps.create-deployment.outputs.deployment_id }}
        state: success

    - name: Update deployment status (failure)
      if: failure()
      uses: chrnorm/deployment-status@9a72af4586197112e0491ea843682b5dc280d806  # v2.0.3
      with:
        token: ${{ github.token }}
        deployment-id: ${{ steps.create-deployment.outputs.deployment_id }}
        state: failure

    - name: Clean up redundant GitHub deployments
      if: success() || failure()
      uses: ./.github/actions/cleanup-redundant-deployments
      with:
        version: ${{ inputs.version }}
        deployment-environment: ${{ inputs.environment }}
        deployment-payload-marker: ${{ inputs.deployment-payload-marker }}

    - name: sleep before success
      shell: bash
      run: |
        sleep 30
