name: Log in to ECR
description: >-
  Authenticates to AWS ECR, allowing access to repositories by Docker tools in subsequent steps.

inputs:
  aws-account-id:
    description: The AWS account hosting the ECR repository
    required: true
  aws-region:
    description: The AWS region in which the ECR repository is hosted in
    required: true

runs:
  using: composite
  steps:
    - name: Configure AWS credentials
      uses: ./.github/actions/aws-auth
      with:
        aws-account-id: ${{ inputs.aws-account-id }}
        aws-region: ${{ inputs.aws-region }}

    - name: Log in to ECR (${{ inputs.aws-account-id }}/${{ inputs.aws-region }})
      uses: aws-actions/amazon-ecr-login@v2
