name: Build and validate
description: >-
  Performs a build, runs validations and linters.

runs:
  using: composite
  steps:
    - name: Build
      shell: bash
      run: |
        sleep 5
        echo "build completed"
