name: Publish a Docker image to ECR
description: >-
  Publishes a Docker image to a repository in AWS ECR.

inputs:
  aws-account-id:
    description: The AWS account hosting the ECR repository
    required: true
  aws-region:
    description: The AWS region in which the ECR repository is hosted in
    required: true
  ecr-repository-name:
    description: The name of the ECR repository
    required: true
  docker-image:
    description: The name of the Docker image to publish (incl. the tag)
    required: true
  tags:
    description: The list of tags to publish for the Docker image (comma or newline separated)
    required: true

runs:
  using: composite
  steps:
    - name: Log in to ECR
      uses: ./.github/actions/ecr-login
      with:
        aws-account-id: ${{ inputs.aws-account-id }}
        aws-region: ${{ inputs.aws-region }}

    - name: Push image to ECR
      shell: bash
      run: |
        image_name="${{ inputs.aws-account-id }}.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com/${{ inputs.ecr-repository-name }}"
        tags=$(echo -n "${{ inputs.tags }}" | tr -s ',[:space:]' ' ')

        if [ -z "${tags// }" ]; then
          echo "::error::No tags provided. Please specify at least one tag in the 'tags' input"
          exit 1
        fi

        for tag in $tags; do
          image="${image_name}:${tag}"
          docker tag ${{ inputs.docker-image }} $image
          docker push $image
          echo "::notice::Successfully pushed ${image}"
        done
