name: CI

on:
  push:

jobs:
  build-test-publish:
    name: Build, test, publish Docker image
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    permissions:
      id-token: write
      contents: read
    environment: 'dev'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set version
        uses: ./.github/actions/set-version

      - name: Initialize build environment
        uses: ./.github/actions/init-build
        with:
          pkg-actor: '${{ secrets.PKG_ACTOR }}'
          pkg-token: '${{ secrets.PKG_TOKEN }}'

      - name: Check code style
        uses: ./.github/actions/style

      - name: Build and validate
        uses: ./.github/actions/build-lint

      - name: Test
        uses: ./.github/actions/test

      - name: Publish Docker image
        if: github.ref == 'refs/heads/main'
        uses: ./.github/actions/ecr-publish
        with:
          aws-account-id: '${{ vars.AWS_ACCOUNT_ID }}'
          aws-region: '${{ vars.AWS_REGION }}'
          ecr-repository-name: 'route-sequencer'
          docker-image: 'route-sequencer:latest'
          tags: |
            ${{ env.VERSION }}

  deploy-dev:
    name: Deploy
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yml
    needs: build-test-publish
    with:
      environment: 'dev'
