name: CI

on:
  push:
    branches-ignore:
      - 'deploy/**'  # XXX deploy or release?
      - 'release/**'
      - 'rollback/**'

jobs:
  build-test-publish:
    name: Build, test, publish Docker image
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    permissions:
      id-token: write
      contents: read
    environment: 'dev'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set version
        uses: ./.github/actions/set-version

      - name: Build and validate
        uses: ./.github/actions/build-lint

      - name: Publish Docker image
        if: github.ref == 'refs/heads/main'
        shell: bash
        run: |
          echo "published docker image"

  deploy-dev:
    name: Deploy to 'dev'
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yml
    needs: build-test-publish
    with:
      environment: 'dev'
