name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        description: The name of the GitHub environment to which the service is being deployed
        type: string
        required: true
      prerequisite-environment:
        description: The name of the GitHub environment that must have a successful prior deployment
        type: string
        required: false
        default: ""  # none

jobs:
  deploy:
    name: Deploy to '${{ inputs.environment }}'
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    permissions:
      id-token: write
      contents: read
      deployments: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set version
        uses: ./.github/actions/set-version

      - name: Deploy service
        uses: ./.github/actions/deploy
        with:
          version: '${{ env.VERSION }}'
          environment: '${{ inputs.environment }}'
          prerequisite-environment: '${{ inputs.prerequisite-environment }}'
