name: Deploy from feature branch

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to 'dev'
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    permissions:
      id-token: write
      contents: read
      deployments: write
    environment: 'dev'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set version
        uses: ./.github/actions/set-version
        with:
          version: 'feature'

      - name: Initialize build environment
        uses: ./.github/actions/init-build
        with:
          pkg-actor: '${{ secrets.PKG_ACTOR }}'
          pkg-token: '${{ secrets.PKG_TOKEN }}'

      - name: Build and validate
        uses: ./.github/actions/build-lint

      - name: Publish Docker image
        uses: ./.github/actions/ecr-publish
        with:
          aws-account-id: '${{ vars.AWS_ACCOUNT_ID }}'
          aws-region: '${{ vars.AWS_REGION }}'
          ecr-repository-name: 'route-sequencer'
          docker-image: 'route-sequencer:latest'
          tags: |
            ${{ env.VERSION }}

      - name: Deploy service
        uses: ./.github/actions/deploy
        with:
          version: '${{ env.VERSION }}'
          environment: 'dev'
          aws-account-id: '${{ vars.AWS_ACCOUNT_ID }}'
          aws-region: '${{ vars.AWS_REGION }}'
          aws-account-id-ecr-src: '${{ vars.AWS_ACCOUNT_ID_ECR_SRC }}'
          aws-region-ecr-src: '${{ vars.AWS_REGION_ECR_SRC }}'
