name: Deploy from feature branch

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to 'dev'
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    permissions:
      id-token: write
      contents: read
      deployments: write
    environment: 'dev'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set version
        uses: ./.github/actions/set-version
        with:
          version: 'feature'

      - name: Build and validate
        uses: ./.github/actions/build-lint

      - name: Publish Docker image
        shell: bash
        run: |
          echo "published docker image"

      - name: Deploy service
        uses: ./.github/actions/deploy
        with:
          version: '${{ env.VERSION }}'
          environment: 'dev'
