name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to deploy to
        type: environment
        required: true
  workflow_call:
    inputs:
      environment:
        description: Environment to deploy to
        type: string
        required: true

jobs:
  deploy:
    name: Deploy to '${{ inputs.environment }}'
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    permissions:
      id-token: write
      contents: read
      deployments: write
    environment: '${{ inputs.environment }}'
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set version
        uses: ./.github/actions/set-version

      - name: Deploy service
        uses: ./.github/actions/deploy
        with:
          version: '${{ env.VERSION }}'
          environment: '${{ inputs.environment }}'
          aws-account-id: '${{ vars.AWS_ACCOUNT_ID }}'
          aws-region: '${{ vars.AWS_REGION }}'
          aws-account-id-ecr-src: '${{ vars.AWS_ACCOUNT_ID_ECR_SRC }}'
          aws-region-ecr-src: '${{ vars.AWS_REGION_ECR_SRC }}'
