name: Deploy to 'stage'

on:
  push:
    tags:
      - deploy/*

jobs:
  deploy:
    name: Deploy to 'stage'
    uses: ./.github/workflows/deploy.yml
    with:
      environment: 'stage'
      prerequisite-environment: 'dev'
