name: Deploy to 'dev'

on:
  workflow_dispatch:

jobs:
  build-publish:
    name: Build and publish Docker image
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    permissions:
      id-token: write
      contents: read
      deployments: write
    environment: 'dev'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set version
        uses: ./.github/actions/set-version
        with:
          version: 'feature'

      - name: Build and validate
        uses: ./.github/actions/build-lint

      - name: Publish Docker image
        shell: bash
        run: |
          echo "published docker image"

      # - name: Deploy service
      #   uses: ./.github/actions/deploy
      #   with:
      #     version: '${{ env.VERSION }}'
      #     environment: 'dev'
      #     prerequisite-environment: 'xxx'

  deploy:
    name: Deploy to 'dev'
    uses: ./.github/workflows/deploy.yml
    with:
      environment: 'dev'
      prerequisite-environment: 'xxx2'
