name: Deploy to 'dev'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to deploy to
        type: environment
        required: true
  workflow_call:
    inputs:
      environment:
        description: Environment to deploy to
        type: string
        required: true

jobs:
  deploy:
    name: Deploy to 'dev'
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    permissions:
      id-token: write
      contents: read
      deployments: write
    environment: 'dev'
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set version
        uses: ./.github/actions/set-version

      - name: Deploy service
        uses: ./.github/actions/deploy
        with:
          version: '${{ env.VERSION }}'
          environment: '${{ inputs.environment }}'
