name: Rollback in 'prod'

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Rollback in 'prod'
    uses: ./.github/workflows/deploy.yml
    with:
      environment: 'prod'
      prerequisite-environment: 'prod'
