name: Tag commit

on:
  workflow_dispatch:
    inputs:
      commit-hash:
        description: Commit to tag
        type: string
        required: true
      tag-name:
        description: Tag name
        type: string
        required: true
      tag-message:
        description: Tag message
        type: string
        required: false

jobs:
  deploy:
    name: Tag commit
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    permissions:
      contents: write # XXX ??
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 100  # allows one of the last 100 commits to be tagged

      - name: Tag commit
        shell: bash
        env:
          COMMIT_HASH: ${{ inputs.commit-hash }}
          TAG_NAME: ${{ inputs.tag-name }}
          TAG_MESSAGE: ${{ inputs.tag-message }}
          GIT_AUTHOR_NAME: ${{ github.actor }}
          GIT_COMMITTER_NAME: ${{ github.actor }}
          GIT_AUTHOR_EMAIL: ${{ github.actor }}@users.noreply.github.com
          GIT_COMMITTER_EMAIL: ${{ github.actor }}@users.noreply.github.com
        run: |
          git tag \
            --annotate "$TAG_NAME" \
            --message "$TAG_MESSAGE" \
            "$COMMIT_HASH"
          git push --tags
          echo "::notice::Commit '$COMMIT_HASH' was tagged with '$TAG_NAME'"
